all_clues:
  - head
  - shoulder
  - hip
  - foot

used_segs:
  - "429"

params:
  stride: 40.0
  mdl: 6000.0
  use_real: true
  used_parts:
    - "429"

data_paths:
  kp: ../data/export/data.pkl
  kp_finished: ../data/export/data_finished.pkl
  sp: ../data/export/sp_merged.pkl
  frames: ../data/export/frames/
  panel_plots: ../data/results/panel_plots/
