all_clues:
  - head
  - shoulder
  - hip
  - foot

used_segs:
  # - "433"

force_rerun: True
test: False
use_space: True
replace_df: True

analysis:
  spatial: False
  temporal: False
  cross_modal: True

plots:
  panels: True

params:
  stride: 40.0
  mdl: 6000.0

paths:
  kp: ../data/sam4d_converted/data.pkl
  kp_finished: ../data/sam4d_converted/data_finished.pkl
  # ground_csv: ../data/sam4d/ground_plane_info.csv
  sp: ../data/export/sp_merged.pkl
  frames: ../data/export/frames/
  panel_plots: ../data/results/panel_plots/
  log: ./experiments/logs/
  results: ../data/results/
